name: Release
on:
  push:
    branches: [ master ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run test
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.SYNCED_GOOGLE_MAPS_API_KEY_SERVICES }}
        GH_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
        NPM_TOKEN: ${{ secrets.NPM_WOMBAT_TOKEN }}
